settings:
  draft: draft07
  regions:
    # US
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - ap-south-1

    # Asia Pacific
    - ap-northeast-3
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-1

    # CA
    - ca-central-1

    # EU
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3

    # South America
    - sa-east-1
  output: /tmp/cfn-schemas/
  single: false
  intrinsics: true

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html
specifications:
  # US Region
  us-east-1: https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  us-east-2: https://dnwj8swjjbsbt.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  us-west-1: https://d68hl49wbnanq.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  us-west-2: https://d201a2mn26r7lk.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  ap-south-1: https://d2senuesg1djtx.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

  # Asia Pacific
  ap-northeast-3: https://d2zq80gdmjim8k.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  ap-northeast-2: https://d1ane3fvebulky.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  ap-southeast-1: https://doigdx0kgq9el.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  ap-southeast-2: https://d2stg8d246z9di.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  ap-northeast-1: https://d33vqc0rt9ld30.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

  # CA
  ca-central-1: https://d2s8ygphhesbe7.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

  # EU
  eu-central-1: https://d1mta8qj7i28i2.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  eu-north-1: https://diy8iv58sj6ba.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  eu-west-1: https://d3teyb21fexa9r.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  eu-west-2: https://d1742qcu2c1ncx.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
  eu-west-3: https://d2d0mfegowb3wk.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

  # South America
  sa-east-1: https://d3c9jyj3w509b0.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

groups:
  default:
    includes:
      - Tag

  networking:
    includes:
      - AWS::EC2.*
    excludes:
      - AWS::EC2::(Spot|Launch|Instance|Volume|Host).*

  serverless:
    includes:
      - AWS::ApiGateway.*
      - AWS::Lambda.*
      - AWS::IAM.*

  3tierAsgApp:
    includes:
      - AWS::ElasticLoadBalancingV2.*
      - AWS::RDS.*
      - AWS::AutoScal.*
      - AWS::IAM.*

  all:
    includes:
      - AWS.*
      - Alexa.*

